# wasm-pack configuration for advanced optimizations

[package]
name = "typetensor-wasm"

[profile.release]
# Enable all wasm-opt optimizations
wasm-opt = [
  "-O4",                              # Maximum optimization level
  "--enable-bulk-memory",             # Enable bulk memory operations
  "--enable-simd",                    # Enable SIMD support
  "--strip-debug",                    # Remove debug sections
  "--strip-producers",                # Remove producers section
  "--vacuum",                         # Remove unused code and data
  "--dce",                           # Dead code elimination
  "--duplicate-function-elimination", # Remove duplicate functions
  "--memory-packing",                # Optimize memory layout
  "--optimize-instructions",         # Optimize individual instructions
  "--coalesce-locals",              # Coalesce local variables
  "--reorder-locals",               # Reorder locals for compression
  "--merge-locals",                 # Merge locals when possible
  "--simplify-globals",             # Simplify global variables
  "--simplify-locals",              # Simplify local variables
  "--precompute",                   # Precompute constant expressions
  "--code-folding",                 # Fold identical code
  "--merge-blocks",                 # Merge basic blocks
  "--remove-unused-names",          # Remove unused names
  "--remove-unused-brs",            # Remove unused branches
  "--remove-unused-module-elements",# Remove unused module elements
  "--reorder-functions",            # Reorder functions for cache
  "--zero-filled-memory",           # Assume zero-filled memory
]