name: Changeset Check

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  check:
    name: Check for changeset
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Check for changeset
        run: |
          # Get the base branch (usually main)
          BASE_BRANCH=${{ github.base_ref }}
          
          # Check if there are any changes to packages
          CHANGED_PACKAGES=$(git diff --name-only origin/$BASE_BRANCH...HEAD | grep -E '^packages/' || true)
          
          # If no package changes, skip changeset check
          if [ -z "$CHANGED_PACKAGES" ]; then
            echo "No package changes detected, skipping changeset check"
            exit 0
          fi
          
          # Check for changesets
          if ! ls .changeset/*.md 2>/dev/null | grep -v README.md > /dev/null; then
            echo "⚠️ No changeset found!"
            echo ""
            echo "This PR includes changes to packages but doesn't have a changeset."
            echo "Please run 'bun changeset' to create a changeset for your changes."
            echo ""
            echo "If this PR doesn't need a release (e.g., internal changes, tests, docs),"
            echo "you can create an empty changeset by running:"
            echo "  bun changeset --empty"
            exit 1
          fi
          
          echo "✅ Changeset found!"

      - name: Comment on PR if changeset is missing
        if: failure()
        uses: actions/github-script@v7
        with:
          script: |
            const comment = `### ⚠️ Missing Changeset
            
            This PR includes changes to packages but doesn't have a changeset. Changesets are required for all changes that affect published packages.
            
            To add a changeset, run:
            \`\`\`bash
            bun changeset
            \`\`\`
            
            Then follow the prompts to:
            1. Select which packages have changed
            2. Choose the version bump type (patch/minor/major)
            3. Write a summary of your changes
            
            If this PR doesn't require a release (e.g., internal refactoring, tests, or documentation), you can create an empty changeset:
            \`\`\`bash
            bun changeset --empty
            \`\`\`
            
            [Learn more about changesets](https://github.com/changesets/changesets/blob/main/docs/adding-a-changeset.md)`;
            
            // Check if we've already commented
            const { data: comments } = await github.rest.issues.listComments({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
            });
            
            const hasComment = comments.some(comment => 
              comment.body.includes('Missing Changeset') && 
              comment.user.type === 'Bot'
            );
            
            if (!hasComment) {
              await github.rest.issues.createComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: context.issue.number,
                body: comment,
              });
            }